// <auto-generated />
using System;
using AdvocateAssist.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AdvocateAssist.Migrations
{
    [DbContext(typeof(AdvocateAssistContext))]
    [Migration("20250709061201_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AdvocateAssist.Entities.Case", b =>
                {
                    b.Property<int>("CaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CaseId"));

                    b.Property<string>("CaseNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CaseId")
                        .HasName("PK__Case__6CAE524CC2674450");

                    b.ToTable("Case", (string)null);

                    b.HasData(
                        new
                        {
                            CaseId = 1,
                            CaseNumber = "CASE-2024-01"
                        },
                        new
                        {
                            CaseId = 2,
                            CaseNumber = "CASE-2024-02"
                        });
                });

            modelBuilder.Entity("AdvocateAssist.Entities.LegalAssistant", b =>
                {
                    b.Property<int>("LegalAssistantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LegalAssistantId"));

                    b.Property<string>("BarLicenseNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("District")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Division")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("datetime");

                    b.Property<string>("LegalAssistantFname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("LegalAssistantFName");

                    b.Property<string>("LegalAssistantLname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("LegalAssistantLName");

                    b.Property<string>("MobileNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("MonthlyStipend")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("NidNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Picture")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LegalAssistantId")
                        .HasName("PK__LegalAss__C876325AA5C50EDD");

                    b.ToTable("LegalAssistant", (string)null);

                    b.HasData(
                        new
                        {
                            LegalAssistantId = 1,
                            BarLicenseNumber = "BAR1234",
                            City = "Mirpur",
                            District = "Dhaka",
                            Division = "Dhaka",
                            Email = "jony@gmail.com",
                            IsActive = true,
                            JoinDate = new DateTime(2022, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LegalAssistantFname = "Jony",
                            LegalAssistantLname = "Sarowar",
                            MobileNo = "01710000001",
                            MonthlyStipend = 15000m,
                            NidNumber = "1234567890",
                            Picture = "jony.jpg"
                        },
                        new
                        {
                            LegalAssistantId = 2,
                            BarLicenseNumber = "BAR5678",
                            City = "Agrabad",
                            District = "Chittagong",
                            Division = "Chittagong",
                            Email = "rafiq@gmail.com",
                            IsActive = true,
                            JoinDate = new DateTime(2023, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LegalAssistantFname = "Rafiq",
                            LegalAssistantLname = "Hasan",
                            MobileNo = "01710000002",
                            MonthlyStipend = 12000m,
                            NidNumber = "1234567890",
                            Picture = "rafiq.png"
                        });
                });

            modelBuilder.Entity("AdvocateAssist.Entities.LegalAssistantCase", b =>
                {
                    b.Property<int>("LegalAssistantCaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LegalAssistantCaseId"));

                    b.Property<int>("CaseId")
                        .HasColumnType("int");

                    b.Property<string>("CaseTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("FilingDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Firnumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("FIRNumber");

                    b.Property<int>("LegalAssistantId")
                        .HasColumnType("int");

                    b.HasKey("LegalAssistantCaseId")
                        .HasName("PK__LegalAss__8C4D842CFFEBE815");

                    b.HasIndex("CaseId");

                    b.HasIndex("LegalAssistantId");

                    b.ToTable("LegalAssistantCase", (string)null);

                    b.HasData(
                        new
                        {
                            LegalAssistantCaseId = 1,
                            CaseId = 1,
                            CaseTitle = "Land Dispute Resolution",
                            FilingDate = new DateTime(2024, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Firnumber = "FIR-001",
                            LegalAssistantId = 1
                        },
                        new
                        {
                            LegalAssistantCaseId = 2,
                            CaseId = 2,
                            CaseTitle = "Family Property Claim",
                            FilingDate = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Firnumber = "FIR-002",
                            LegalAssistantId = 2
                        });
                });

            modelBuilder.Entity("AdvocateAssist.Entities.LegalAssistantCase", b =>
                {
                    b.HasOne("AdvocateAssist.Entities.Case", "Case")
                        .WithMany("LegalAssistantCases")
                        .HasForeignKey("CaseId")
                        .IsRequired()
                        .HasConstraintName("FK__LegalAssi__CaseI__286302EC");

                    b.HasOne("AdvocateAssist.Entities.LegalAssistant", "LegalAssistant")
                        .WithMany("LegalAssistantCases")
                        .HasForeignKey("LegalAssistantId")
                        .IsRequired()
                        .HasConstraintName("FK__LegalAssi__Legal__29572725");

                    b.Navigation("Case");

                    b.Navigation("LegalAssistant");
                });

            modelBuilder.Entity("AdvocateAssist.Entities.Case", b =>
                {
                    b.Navigation("LegalAssistantCases");
                });

            modelBuilder.Entity("AdvocateAssist.Entities.LegalAssistant", b =>
                {
                    b.Navigation("LegalAssistantCases");
                });
#pragma warning restore 612, 618
        }
    }
}
